cmake_minimum_required(VERSION 3.22)
project(sb_eq32 LANGUAGES CXX)
set(CMAKE_CXX_STANDARD 17)
set(CMAKE_CXX_STANDARD_REQUIRED ON)
add_library(sb_eq32_core STATIC src/sb_eq32.cpp)
target_include_directories(sb_eq32_core PUBLIC include)
if(ANDROID)
    add_library(sb_eq32_jni SHARED src/sb_eq32.cpp src/sb_eq32_jni.cpp)
    target_include_directories(sb_eq32_jni PRIVATE include)
    find_library(log-lib log)
    target_link_libraries(sb_eq32_jni ${log-lib})
endif()
